# Basic
title: WoodGhost
subtitle: 渡头余落日 墟里上孤烟
welcome_message: This place is for little ghost and her fellows to read, write and learn. Welcome to this world :)
description: Poems & Offshore
# creator:

url: "http://woodghost.github.io"

baseurl: /myblog

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: ''}
    - {title: Life, description: My Journeys, url: ''}
    - {title: About, description: Self Introduction, url: ''}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: 2576328977
    github: woodghost
    twitter: woodghost36
    gplus: 117752045392286741953
    mail: woodghost0960@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
